### ISSUE TITLE
Create Document to Image conversion api

### ISSUE THREAD

**Issue by anubhav-mahajan** [anubhav-mahajan/doc-to-img-converter#1]
## Background

Client has a requirement where in an API needs to be exposed which will do a basic conversion of a document to Image based on some parameters. The document can be of type **pdf, doc or docx** and the converted image for each page should be either a **png or a jpg file**. The parameters could be some options which could be specific to image resolution like DPI and quality. The API should also have a authentication mechanism, so that it can be securely hosted. 

## Requirement
- [ ] #2
- [ ] The API could be hosted in any environment  **Windows, Linux or MacOS.**
- [ ] An API should be exposed for end user to consume. It should allow the consumer to upload the file using http post request with some options. 
- [ ] The API should have a configurable path on the server where the images are stored.
- [ ] Expose other API to help user download the converted files, if they need it. _(Could be a part of future scope.)_

## Design flow diagram
![doc to image converter arch](https://user-images.githubusercontent.com/63402464/203637436-8848a202-5f1f-4382-8691-7a1684798e64.png)
